name: Tests

on:
  pull_request:

jobs:
  website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
